### PR TITLE
Add COORDINATE to DTS Service Request

### LINKED ISSUE #20117: Add 'COORDINATE' as new value in DTS Service Request Form application dropdown
> What application are you using?

Other / Not sure

> Describe the problem.

On the DTS Service Request Form, please create a new value in the 'What Application are you using' field for COORDINATE. 

> Describe the outcome you'd like to see when this feature is implemented.

None

> Describe any workarounds you currently have in place or alternative solutions you've considered.

no

> Is there anything else we should know?

Preferably by January

> Requested By
Tracy L.

Request ID: DTS24-119625

### PR DESCRIPTION
**Pull request by patrickm02L**
## Description

Closes [#20117](https://github.com/cityofaustin/atd-data-tech/issues/20117)

Adding this tag will make sure that Service Requests can be labeled `Product: COORDINATE` from the intake form. 

## Testing
Review new option has been added

## Steps to update
- [X] Add `Product: COORDINATE` to github labels
- [x] Add `Product: COORDINATE` to field_399 in Knack
- [ ] ~~Pause Airflow DAG - atd_service_bot_issue_intake_production~~
- [ ] ~~Let service desk know SRs are paused~~
- [x] Merge
- [ ] ~~Restart Airflow DAG~~
- [x] Send a Test SR to make sure everything works

### CODE REVIEW

**Review by johnclary — COMMENTED** [review]
👍 looks good.

i'm curious what the others think, but for this kind of change I don't think you need to pause the airflow DAG before you merge. you can skip that step.

**Review by johnclary — APPROVED** [review]

**Comment by mddilley** [comment]
@johnclary I was thinking that too but wasn't sure. After reading through the [docs](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/service-bot-process) again, I think that that is right. The Airflow DAG pause/unpause can be skipped but wouldn't hurt either.

**Review by mddilley — APPROVED** [review]
Looks great to me! 🗺️ 😎

**Comment by patrickm02L** [comment]
Y'all were right. I didn't need to paused the DAG.

**Pull request merged**
